//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiEnquete.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApiEnqueteEntities : DbContext
    {
        public ApiEnqueteEntities()
            : base("name=ApiEnqueteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<options> options { get; set; }
        public virtual DbSet<poll> poll { get; set; }
        public virtual DbSet<stats> stats { get; set; }
        public virtual DbSet<vote> vote { get; set; }
    }
}
