//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiEnquete.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class options
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public options()
        {
            this.vote = new HashSet<vote>();
        }
    
        public int option_id { get; set; }
        public string option_description { get; set; }
        public Nullable<int> poll_id { get; set; }
    
        public virtual poll poll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vote> vote { get; set; }
    }
}
