//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiEnquete.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stats
    {
        public int stats_id { get; set; }
        public Nullable<int> poll_id { get; set; }
    
        public virtual poll poll { get; set; }
    }
}
